/** names of background functions that can be called from popup */
export const FUNCTIONS = {
  getSupportedTabs: "getSupportedTabs",
  getMostImportantTabId: "getMostImportantTabId",
  getTabType: "getTabType",
  switchToTab: "switchToTab",
  addPlaylistTrackData: "addPlaylistTrackData",
  startPlaying: "startPlaying",
  playTrack: "playTrack",
  next: "next",
  previous: "previous",
  stopPlaying: "stopPlaying",
  reshuffle: "reshuffle",
  getPlaylistByTabId: "getPlaylistByTabId",
  previewPlaylist: "previewPlaylist",
  getTrackByTabUrl: "getTrackByTabUrl",
  guessTrackInfo: "guessTrackInfo",
  editTrack: "editTrack",
  searchOtherSite: "searchOtherSite",
  getAllArtists: "getAllArtists",
  getTrackArtists: "getTrackArtists",
  artistMatch: "artistMatch",
  createArtist: "createArtist",
  getAllTags: "getAllTags",
  getTrackTags: "getTrackTags",
  createTag: "createTag",
  createTrack: "createTrack",
  saveBackup: "saveBackup",
  loadBackup: "loadBackup",
};
